[workspace]
resolver = "2"
members = [
    "crates/polyfont-core",
    "crates/polyfont-config",
    "crates/polyfont-scope",
    "crates/polyfont-cli",
    "crates/polyfont-lsp",
    "crates/polyfont-parse",
    "crates/polyfont-fonts",
    "crates/polyfont-themes",
    "crates/polyfont-render",
]

[workspace.package]
version = "0.10.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/WyattAu/polyfont"
rust-version = "1.85"
description = "Per-token font highlighting for code editors"
documentation = "https://docs.rs/polyfont-core"

[workspace.dependencies]
polyfont-core = { path = "crates/polyfont-core", version = "0.10.0" }
polyfont-config = { path = "crates/polyfont-config", version = "0.10.0" }
polyfont-scope = { path = "crates/polyfont-scope", version = "0.10.0" }
polyfont-parse = { path = "crates/polyfont-parse", version = "0.10.0" }
polyfont-fonts = { path = "crates/polyfont-fonts", version = "0.10.0" }
polyfont-themes = { path = "crates/polyfont-themes", version = "0.10.0" }
polyfont-lsp = { path = "crates/polyfont-lsp", version = "0.10.0" }
polyfont-cli = { path = "crates/polyfont-cli", version = "0.10.0" }
polyfont-render = { path = "crates/polyfont-render", version = "0.10.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tower-lsp = "0.20"
walkdir = "2"
