use std::path::{Path, PathBuf};

use polyfont_config::PolyfontConfig;
use serde::{Deserialize, Serialize};

use crate::ThemeError;

pub struct ThemeShare;

impl ThemeShare {
    pub fn share_as_gist(config: &PolyfontConfig, description: &str) -> Result<String, ThemeError> {
        let toml_content = toml::to_string_pretty(config)?;
        Ok(format!(
            "# {description}\n#\n# Generated by polyfont theme share\n\n{toml_content}"
        ))
    }

    pub fn fetch_from_url(_url: &str) -> Result<PolyfontConfig, ThemeError> {
        Err(ThemeError::DownloadDisabled)
    }

    pub fn save_to_project(
        config: &PolyfontConfig,
        project_dir: &Path,
    ) -> Result<PathBuf, ThemeError> {
        let default_family = config
            .default
            .as_ref()
            .map(|d| d.family.as_str())
            .unwrap_or("theme");
        let filename = format!("{}.toml", default_family.to_lowercase().replace(' ', "-"));

        let themes_dir = project_dir.join(".polyfont").join("themes");
        std::fs::create_dir_all(&themes_dir)?;

        let path = themes_dir.join(&filename);
        let content = toml::to_string_pretty(config)?;
        std::fs::write(&path, content)?;

        Ok(path)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeLockEntry {
    pub name: String,
    pub url: String,
    pub sha256: String,
    pub applied_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeLockfile {
    pub themes: Vec<ThemeLockEntry>,
}

impl ThemeLockfile {
    pub fn load(path: &Path) -> Result<Self, ThemeError> {
        let content = std::fs::read_to_string(path)?;
        let lockfile: Self = toml::from_str(&content)?;
        Ok(lockfile)
    }

    pub fn save(&self, path: &Path) -> Result<(), ThemeError> {
        let content = toml::to_string_pretty(self)?;
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn add_theme(&mut self, name: &str, url: &str, sha256: &str) {
        self.themes.push(ThemeLockEntry {
            name: name.to_string(),
            url: url.to_string(),
            sha256: sha256.to_string(),
            applied_at: chrono_now_or_empty(),
        });
    }
}

fn chrono_now_or_empty() -> String {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs().to_string())
        .unwrap_or_default()
}

pub struct ThemeDiscovery;

impl ThemeDiscovery {
    pub fn discover_in_project(project_dir: &Path) -> Vec<PathBuf> {
        let themes_dir = project_dir.join(".polyfont").join("themes");
        if !themes_dir.is_dir() {
            return Vec::new();
        }

        let mut results = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&themes_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().is_some_and(|ext| ext == "toml") {
                    results.push(path);
                }
            }
        }
        results.sort();
        results
    }

    pub fn discover_remote(lockfile: &ThemeLockfile) -> Vec<ThemeLockEntry> {
        lockfile.themes.clone()
    }
}

#[cfg(test)]
mod tests {
    use polyfont_config::{DefaultFontConfig, FontConfig, RuleConfig};
    use polyfont_core::{FontStyle, FontWeight};

    use super::*;

    fn sample_config() -> PolyfontConfig {
        PolyfontConfig {
            version: 1,
            default: Some(DefaultFontConfig {
                family: "Fira Code".to_string(),
                fallbacks: vec![],
                weight: FontWeight::default(),
                style: FontStyle::default(),
                size: None,
                axes: vec![],
            }),
            rules: vec![RuleConfig {
                scope: "keyword".to_string(),
                font: FontConfig {
                    family: "Maple Mono".to_string(),
                    fallbacks: vec![],
                    weight: FontWeight::Bold,
                    style: FontStyle::default(),
                    size: None,
                    axes: vec![],
                },
            }],
        }
    }

    #[test]
    fn test_theme_share_produces_toml() {
        let config = sample_config();
        let result = ThemeShare::share_as_gist(&config, "test theme").unwrap();
        assert!(result.starts_with("# test theme"));
        assert!(result.contains("Fira Code"));
        assert!(result.contains("Maple Mono"));

        let toml_body = result
            .lines()
            .filter(|line| !line.starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: PolyfontConfig = toml::from_str(&toml_body).unwrap();
        assert_eq!(parsed.version, 1);
        assert_eq!(parsed.rules.len(), 1);
    }

    fn test_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join("polyfont-test").join(name);
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_theme_lockfile_roundtrip() {
        let dir = test_dir("lockfile_roundtrip");
        let path = dir.join("theme.lock");

        let mut lockfile = ThemeLockfile { themes: vec![] };
        lockfile.add_theme("dark", "https://example.com/dark.toml", "abc123");
        lockfile.add_theme("light", "https://example.com/light.toml", "def456");

        lockfile.save(&path).unwrap();
        let loaded = ThemeLockfile::load(&path).unwrap();

        assert_eq!(loaded.themes.len(), 2);
        assert_eq!(loaded.themes[0].name, "dark");
        assert_eq!(loaded.themes[0].url, "https://example.com/dark.toml");
        assert_eq!(loaded.themes[0].sha256, "abc123");
        assert_eq!(loaded.themes[1].name, "light");
    }

    #[test]
    fn test_theme_discovery_empty_dir() {
        let dir = test_dir("discovery_empty");
        let found = ThemeDiscovery::discover_in_project(&dir);
        assert!(found.is_empty());
    }

    #[test]
    fn test_save_to_project_creates_dir() {
        let dir = test_dir("save_to_project");
        let project = dir.join("project");
        let config = sample_config();

        let result = ThemeShare::save_to_project(&config, &project).unwrap();

        assert!(result.exists());
        assert!(result.to_string_lossy().contains(".polyfont/themes"));
        assert!(result.to_string_lossy().ends_with("fira-code.toml"));

        let content = std::fs::read_to_string(&result).unwrap();
        let parsed: PolyfontConfig = toml::from_str(&content).unwrap();
        assert_eq!(parsed.version, 1);
    }
}
