use std::path::{Path, PathBuf};

use polyfont_config::PolyfontConfig;
use serde::{Deserialize, Serialize};

use crate::ThemeError;

/// Theme sharing and project-level persistence utilities.
pub struct ThemeShare;

impl ThemeShare {
    /// Format a config as a shareable TOML string with a header comment.
    ///
    /// # Errors
    ///
    /// Returns [`ThemeError::TomlSerialize`] if the config cannot be serialized.
    pub fn format_gist_content(
        config: &PolyfontConfig,
        description: &str,
    ) -> Result<String, ThemeError> {
        let toml_content = toml::to_string_pretty(config)?;
        Ok(format!(
            "# {description}\n#\n# Generated by polyfont theme share\n\n{toml_content}"
        ))
    }

    /// Fetch a polyfont config from a remote URL. Requires the `download` feature.
    ///
    /// # Errors
    ///
    /// Returns [`ThemeError::DownloadDisabled`] if the `download` feature is not
    /// enabled, [`ThemeError::Validation`] on HTTP failure, or
    /// [`ThemeError::Toml`] if the response body is not valid TOML.
    pub fn fetch_from_url(url: &str) -> Result<PolyfontConfig, ThemeError> {
        #[cfg(feature = "download")]
        {
            Self::fetch_from_url_impl(url)
        }
        #[cfg(not(feature = "download"))]
        {
            let _ = url;
            Err(ThemeError::DownloadDisabled)
        }
    }

    /// Save a config to a project's `.polyfont/themes/` directory.
    ///
    /// # Errors
    ///
    /// Returns [`ThemeError::Io`] if directory creation or writing fails, or
    /// [`ThemeError::TomlSerialize`] if the config cannot be serialized.
    pub fn save_to_project(
        config: &PolyfontConfig,
        project_dir: &Path,
    ) -> Result<PathBuf, ThemeError> {
        let default_family = config
            .default
            .as_ref()
            .map(|d| d.family.as_str())
            .unwrap_or("theme");
        let filename = format!("{}.toml", default_family.to_lowercase().replace(' ', "-"));

        let themes_dir = project_dir.join(".polyfont").join("themes");
        std::fs::create_dir_all(&themes_dir)?;

        let path = themes_dir.join(&filename);
        let content = toml::to_string_pretty(config)?;
        std::fs::write(&path, content)?;

        Ok(path)
    }
}

/// An entry in the theme lockfile tracking remote themes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeLockEntry {
    pub name: String,
    pub url: String,
    pub sha256: String,
    pub applied_at: String,
}

/// Lockfile tracking applied remote themes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThemeLockfile {
    pub themes: Vec<ThemeLockEntry>,
}

impl ThemeLockfile {
    pub fn load(path: &Path) -> Result<Self, ThemeError> {
        let content = std::fs::read_to_string(path)?;
        let lockfile: Self = toml::from_str(&content)?;
        Ok(lockfile)
    }

    pub fn save(&self, path: &Path) -> Result<(), ThemeError> {
        let content = toml::to_string_pretty(self)?;
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn add_theme(&mut self, name: &str, url: &str, sha256: &str) {
        self.themes.push(ThemeLockEntry {
            name: name.to_string(),
            url: url.to_string(),
            sha256: sha256.to_string(),
            applied_at: chrono_now_or_empty(),
        });
    }
}

fn chrono_now_or_empty() -> String {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs().to_string())
        .unwrap_or_default()
}

#[cfg(feature = "download")]
impl ThemeShare {
    fn fetch_from_url_impl(url: &str) -> Result<PolyfontConfig, ThemeError> {
        let response = reqwest::blocking::Client::new()
            .get(url)
            .send()
            .map_err(|e| ThemeError::Io(std::io::Error::other(e.to_string())))?;

        if !response.status().is_success() {
            return Err(ThemeError::Validation(format!(
                "failed to fetch theme from {url}: HTTP {}",
                response.status()
            )));
        }

        let content = response.text().map_err(|e| {
            ThemeError::Io(std::io::Error::other(format!(
                "failed to read response: {e}"
            )))
        })?;

        let config: PolyfontConfig = toml::from_str(&content)?;
        Ok(config)
    }
}

/// Discovers theme files in project directories.
pub struct ThemeDiscovery;

impl ThemeDiscovery {
    /// Find all `.toml` theme files in a project's `.polyfont/themes/` directory.
    pub fn discover_in_project(project_dir: &Path) -> Vec<PathBuf> {
        let themes_dir = project_dir.join(".polyfont").join("themes");
        if !themes_dir.is_dir() {
            return Vec::new();
        }

        let mut results = Vec::new();
        if let Ok(entries) = std::fs::read_dir(&themes_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.extension().is_some_and(|ext| ext == "toml") {
                    results.push(path);
                }
            }
        }
        results.sort();
        results
    }

    /// List themes from a lockfile.
    pub fn discover_remote(lockfile: &ThemeLockfile) -> Vec<ThemeLockEntry> {
        lockfile.themes.clone()
    }
}

/// An entry in the remote theme registry.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemoteThemeEntry {
    pub name: String,
    pub author: String,
    pub source: String,
    #[serde(default)]
    pub fonts: Vec<String>,
    #[serde(default)]
    pub scope_count: u32,
    #[serde(default)]
    pub description: String,
}

/// A registry of remotely available themes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RemoteThemeRegistry {
    pub themes: Vec<RemoteThemeEntry>,
}

impl RemoteThemeRegistry {
    /// The URL of the official polyfont theme registry.
    pub const REGISTRY_URL: &'static str =
        "https://raw.githubusercontent.com/WyattAu/polyfont/main/themes/themes.json";

    /// Create a registry from a JSON string.
    pub fn from_json(json: &str) -> Result<Self, ThemeError> {
        let registry: Self = serde_json::from_str(json)?;
        Ok(registry)
    }

    /// Serialize the registry to JSON.
    pub fn to_json(&self) -> Result<String, ThemeError> {
        Ok(serde_json::to_string_pretty(self)?)
    }

    /// Find a theme by name (case-insensitive).
    #[must_use]
    pub fn find(&self, name: &str) -> Option<&RemoteThemeEntry> {
        self.themes
            .iter()
            .find(|t| t.name.eq_ignore_ascii_case(name))
    }

    /// List all theme names.
    #[must_use]
    pub fn list_names(&self) -> Vec<&str> {
        self.themes.iter().map(|t| t.name.as_str()).collect()
    }
}

impl Default for RemoteThemeRegistry {
    fn default() -> Self {
        Self {
            themes: vec![
                RemoteThemeEntry {
                    name: "monaspace-dark".to_string(),
                    author: "polyfont".to_string(),
                    source: "https://raw.githubusercontent.com/WyattAu/polyfont/main/themes/monaspace-dark.toml".to_string(),
                    fonts: vec!["Monaspace Argon".to_string(), "Monaspace Neon".to_string(), "Monaspace Krypton".to_string(), "Monaspace Radon".to_string()],
                    scope_count: 18,
                    description: "Full Monaspace variable-font family with per-scope differentiation.".to_string(),
                },
                RemoteThemeEntry {
                    name: "minimal".to_string(),
                    author: "polyfont".to_string(),
                    source: "https://raw.githubusercontent.com/WyattAu/polyfont/main/themes/minimal.toml".to_string(),
                    fonts: vec!["JetBrains Mono".to_string(), "IBM Plex Mono".to_string()],
                    scope_count: 4,
                    description: "Two-font setup: JetBrains Mono for code, IBM Plex Mono for comments.".to_string(),
                },
                RemoteThemeEntry {
                    name: "serif-mono".to_string(),
                    author: "polyfont".to_string(),
                    source: "https://raw.githubusercontent.com/WyattAu/polyfont/main/themes/serif-mono.toml".to_string(),
                    fonts: vec!["JetBrains Mono".to_string(), "Source Serif Pro".to_string()],
                    scope_count: 8,
                    description: "Monospace for code, serif for comments and documentation.".to_string(),
                },
            ],
        }
    }
}

#[cfg(test)]
mod tests {
    use polyfont_config::{DefaultFontConfig, FontConfig, RuleConfig};
    use polyfont_core::{FontStyle, FontWeight};

    use super::*;

    fn sample_config() -> PolyfontConfig {
        PolyfontConfig {
            version: 1,
            default: Some(DefaultFontConfig {
                family: "Fira Code".to_string(),
                fallbacks: vec![],
                weight: FontWeight::default(),
                style: FontStyle::default(),
                size: None,
                axes: vec![],
            }),
            rules: vec![RuleConfig {
                scope: "keyword".to_string(),
                font: FontConfig {
                    family: "Maple Mono".to_string(),
                    fallbacks: vec![],
                    weight: FontWeight::Bold,
                    style: FontStyle::default(),
                    size: None,
                    axes: vec![],
                },
            }],
        }
    }

    #[test]
    fn test_theme_share_produces_toml() {
        let config = sample_config();
        let result = ThemeShare::format_gist_content(&config, "test theme").unwrap();
        assert!(result.starts_with("# test theme"));
        assert!(result.contains("Fira Code"));
        assert!(result.contains("Maple Mono"));

        let toml_body = result
            .lines()
            .filter(|line| !line.starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        let parsed: PolyfontConfig = toml::from_str(&toml_body).unwrap();
        assert_eq!(parsed.version, 1);
        assert_eq!(parsed.rules.len(), 1);
    }

    fn test_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join("polyfont-test").join(name);
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_theme_lockfile_roundtrip() {
        let dir = test_dir("lockfile_roundtrip");
        let path = dir.join("theme.lock");

        let mut lockfile = ThemeLockfile { themes: vec![] };
        lockfile.add_theme("dark", "https://example.com/dark.toml", "abc123");
        lockfile.add_theme("light", "https://example.com/light.toml", "def456");

        lockfile.save(&path).unwrap();
        let loaded = ThemeLockfile::load(&path).unwrap();

        assert_eq!(loaded.themes.len(), 2);
        assert_eq!(loaded.themes[0].name, "dark");
        assert_eq!(loaded.themes[0].url, "https://example.com/dark.toml");
        assert_eq!(loaded.themes[0].sha256, "abc123");
        assert_eq!(loaded.themes[1].name, "light");
    }

    #[test]
    fn test_theme_discovery_empty_dir() {
        let dir = test_dir("discovery_empty");
        let found = ThemeDiscovery::discover_in_project(&dir);
        assert!(found.is_empty());
    }

    #[test]
    fn test_save_to_project_creates_dir() {
        let dir = test_dir("save_to_project");
        let project = dir.join("project");
        let config = sample_config();

        let result = ThemeShare::save_to_project(&config, &project).unwrap();

        assert!(result.exists());
        assert!(result.to_string_lossy().contains(".polyfont"));
        assert!(result.to_string_lossy().contains("themes"));
        assert!(result.to_string_lossy().ends_with("fira-code.toml"));

        let content = std::fs::read_to_string(&result).unwrap();
        let parsed: PolyfontConfig = toml::from_str(&content).unwrap();
        assert_eq!(parsed.version, 1);
    }

    #[test]
    fn test_remote_registry_default() {
        let registry = RemoteThemeRegistry::default();
        assert!(!registry.themes.is_empty());
        assert!(registry.find("monaspace-dark").is_some());
        assert!(registry.find("nonexistent").is_none());
    }

    #[test]
    fn test_remote_registry_roundtrip() {
        let registry = RemoteThemeRegistry::default();
        let json = registry.to_json().unwrap();
        let parsed = RemoteThemeRegistry::from_json(&json).unwrap();
        assert_eq!(parsed.themes.len(), registry.themes.len());
        assert_eq!(parsed.list_names(), registry.list_names());
    }
}
